---
- hosts: all
  sudo: True
  vars:
      src_dir: /usr/local/src/scade2b
  tasks:
    - name: Install packages
      apt: pkg={{item}} state=installed
      with_items:
         - git
         - ocaml-nox
         - gdm
         - xfce4
    - name: Create cercles user
      user: name=cercles
    - name: Create session directory
      file: path=/var/lib/AccountsService/users state=directory
    - name: Set default session
      action: copy
      args:
          src: AccountService
          dest: /var/lib/AccountsService/users/cercles
    - name: Setup automatic login
      action: copy
      args:
          src: gdm-custom.conf
          dest: /etc/gdm/custom.conf
      notify: Restart gdm
    - name: Checkout scade2b
      action: git
      args:
          repo: https://github.com/cercles/scade2b.git
          dest: "{{src_dir}}"
          version: c380dec2
    - name: Build scade2b
      command: make
      args:
          chdir: "{{src_dir}}/scade2b"
          creates: scade2b
    - name: Install scade2b
      command: cp {{src_dir}}/scade2b/scade2b /usr/local/bin/
      args:
          creates: /usr/local/bin/scade2b
  handlers:
    - name: Restart gdm
      service: name=gdm state=restarted
