---
- hosts: all
  sudo: True
  tasks:
    - name: Install packages
      apt: pkg={{item}} state=installed
      with_items:
         - git
         - ocaml-nox
    - name: Checkout scade2b
      git: repo=https://github.com/cercles/scade2b.git
           dest=src
           version=c380dec2
    - name: Build scade2b
      command: make
      args:
          chdir: src/scade2b
          creates: scade2b
    - name: Install scade2b
      command: cp src/scade2b/scade2b /usr/local/bin/
      args:
          creates: /usr/local/bin/scade2b
